
spring:
  #freemarker
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftlh
  #Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

#Context-path
server:
  servlet:
    context-path: /business-owner/service

  port: 8083

  error:
    path: /business-owner/service/error
    whitelabel:
      enabled: false