
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration, classpath:db/local-and-test

  #datasource
  datasource:
    url: jdbc:h2:mem:localdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: localadmin
    password: localpass

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true

  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
